version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  build_and_test:
    executor: 
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m unittest discover -s test -p "crawl_tests.py"
workflows:
  main:
    jobs:
      - build_and_test
